//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salvadorpos.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.QuickBooksWebRestSoap")]
    public interface QuickBooksWebRestSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaClientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaClientes", ReplyAction="*")]
        salvadorpos.ServiceReference1.ListaClientesResponse ListaClientes(salvadorpos.ServiceReference1.ListaClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaClientesResponse> ListaClientesAsync(salvadorpos.ServiceReference1.ListaClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idcliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDataExtCustomer", ReplyAction="*")]
        salvadorpos.ServiceReference1.ListaDataExtCustomerResponse ListaDataExtCustomer(salvadorpos.ServiceReference1.ListaDataExtCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDataExtCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaDataExtCustomerResponse> ListaDataExtCustomerAsync(salvadorpos.ServiceReference1.ListaDataExtCustomerRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaPriceLevelsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaPriceLevels", ReplyAction="*")]
        salvadorpos.ServiceReference1.ListaPriceLevelsResponse ListaPriceLevels(salvadorpos.ServiceReference1.ListaPriceLevelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaPriceLevels", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaPriceLevelsResponse> ListaPriceLevelsAsync(salvadorpos.ServiceReference1.ListaPriceLevelsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaFactura", ReplyAction="*")]
        salvadorpos.ServiceReference1.InsertaFacturaResponse InsertaFactura(salvadorpos.ServiceReference1.InsertaFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.InsertaFacturaResponse> InsertaFacturaAsync(salvadorpos.ServiceReference1.InsertaFacturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento productos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pruebaJSON", ReplyAction="*")]
        salvadorpos.ServiceReference1.pruebaJSONResponse pruebaJSON(salvadorpos.ServiceReference1.pruebaJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pruebaJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.pruebaJSONResponse> pruebaJSONAsync(salvadorpos.ServiceReference1.pruebaJSONRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaTerminosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaTerminos", ReplyAction="*")]
        salvadorpos.ServiceReference1.ListaTerminosResponse ListaTerminos(salvadorpos.ServiceReference1.ListaTerminosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaTerminos", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaTerminosResponse> ListaTerminosAsync(salvadorpos.ServiceReference1.ListaTerminosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaMensajesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaMensajes", ReplyAction="*")]
        salvadorpos.ServiceReference1.ListaMensajesResponse ListaMensajes(salvadorpos.ServiceReference1.ListaMensajesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaMensajes", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaMensajesResponse> ListaMensajesAsync(salvadorpos.ServiceReference1.ListaMensajesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListID del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerAdd", ReplyAction="*")]
        salvadorpos.ServiceReference1.CustomerAddResponse CustomerAdd(salvadorpos.ServiceReference1.CustomerAddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.CustomerAddResponse> CustomerAddAsync(salvadorpos.ServiceReference1.CustomerAddRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento customerID del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomFieldAdd", ReplyAction="*")]
        salvadorpos.ServiceReference1.CustomFieldAddResponse CustomFieldAdd(salvadorpos.ServiceReference1.CustomFieldAddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomFieldAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.CustomFieldAddResponse> CustomFieldAddAsync(salvadorpos.ServiceReference1.CustomFieldAddRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaImpuestosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaImpuestos", ReplyAction="*")]
        salvadorpos.ServiceReference1.ListaImpuestosResponse ListaImpuestos(salvadorpos.ServiceReference1.ListaImpuestosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaImpuestos", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaImpuestosResponse> ListaImpuestosAsync(salvadorpos.ServiceReference1.ListaImpuestosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idcliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaBodegasItem", ReplyAction="*")]
        salvadorpos.ServiceReference1.ListaBodegasItemResponse ListaBodegasItem(salvadorpos.ServiceReference1.ListaBodegasItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaBodegasItem", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaBodegasItemResponse> ListaBodegasItemAsync(salvadorpos.ServiceReference1.ListaBodegasItemRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaArticulosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaArticulos", ReplyAction="*")]
        salvadorpos.ServiceReference1.ListaArticulosResponse ListaArticulos(salvadorpos.ServiceReference1.ListaArticulosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaArticulos", ReplyAction="*")]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaArticulosResponse> ListaArticulosAsync(salvadorpos.ServiceReference1.ListaArticulosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaClientes", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaClientesRequestBody Body;
        
        public ListaClientesRequest() {
        }
        
        public ListaClientesRequest(salvadorpos.ServiceReference1.ListaClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaClientesRequestBody {
        
        public ListaClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaClientesResponseBody Body;
        
        public ListaClientesResponse() {
        }
        
        public ListaClientesResponse(salvadorpos.ServiceReference1.ListaClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaClientesResult;
        
        public ListaClientesResponseBody() {
        }
        
        public ListaClientesResponseBody(salvadorpos.ServiceReference1.ArrayOfString[] ListaClientesResult) {
            this.ListaClientesResult = ListaClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaDataExtCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaDataExtCustomer", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaDataExtCustomerRequestBody Body;
        
        public ListaDataExtCustomerRequest() {
        }
        
        public ListaDataExtCustomerRequest(salvadorpos.ServiceReference1.ListaDataExtCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaDataExtCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idcliente;
        
        public ListaDataExtCustomerRequestBody() {
        }
        
        public ListaDataExtCustomerRequestBody(string idcliente) {
            this.idcliente = idcliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaDataExtCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaDataExtCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaDataExtCustomerResponseBody Body;
        
        public ListaDataExtCustomerResponse() {
        }
        
        public ListaDataExtCustomerResponse(salvadorpos.ServiceReference1.ListaDataExtCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaDataExtCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaDataExtCustomerResult;
        
        public ListaDataExtCustomerResponseBody() {
        }
        
        public ListaDataExtCustomerResponseBody(salvadorpos.ServiceReference1.ArrayOfString[] ListaDataExtCustomerResult) {
            this.ListaDataExtCustomerResult = ListaDataExtCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaPriceLevelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaPriceLevels", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaPriceLevelsRequestBody Body;
        
        public ListaPriceLevelsRequest() {
        }
        
        public ListaPriceLevelsRequest(salvadorpos.ServiceReference1.ListaPriceLevelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaPriceLevelsRequestBody {
        
        public ListaPriceLevelsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaPriceLevelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaPriceLevelsResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaPriceLevelsResponseBody Body;
        
        public ListaPriceLevelsResponse() {
        }
        
        public ListaPriceLevelsResponse(salvadorpos.ServiceReference1.ListaPriceLevelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaPriceLevelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaPriceLevelsResult;
        
        public ListaPriceLevelsResponseBody() {
        }
        
        public ListaPriceLevelsResponseBody(salvadorpos.ServiceReference1.ArrayOfString[] ListaPriceLevelsResult) {
            this.ListaPriceLevelsResult = ListaPriceLevelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaFactura", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.InsertaFacturaRequestBody Body;
        
        public InsertaFacturaRequest() {
        }
        
        public InsertaFacturaRequest(salvadorpos.ServiceReference1.InsertaFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertaFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string template;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TxnDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DueDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ShipDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string termino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string memo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ItemSalesTax;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CustomerMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string productos;
        
        public InsertaFacturaRequestBody() {
        }
        
        public InsertaFacturaRequestBody(string cliente, string template, string TxnDate, string DueDate, string ShipDate, string termino, string memo, string ItemSalesTax, string CustomerMsg, string productos) {
            this.cliente = cliente;
            this.template = template;
            this.TxnDate = TxnDate;
            this.DueDate = DueDate;
            this.ShipDate = ShipDate;
            this.termino = termino;
            this.memo = memo;
            this.ItemSalesTax = ItemSalesTax;
            this.CustomerMsg = CustomerMsg;
            this.productos = productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.InsertaFacturaResponseBody Body;
        
        public InsertaFacturaResponse() {
        }
        
        public InsertaFacturaResponse(salvadorpos.ServiceReference1.InsertaFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertaFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertaFacturaResult;
        
        public InsertaFacturaResponseBody() {
        }
        
        public InsertaFacturaResponseBody(string InsertaFacturaResult) {
            this.InsertaFacturaResult = InsertaFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pruebaJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pruebaJSON", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.pruebaJSONRequestBody Body;
        
        public pruebaJSONRequest() {
        }
        
        public pruebaJSONRequest(salvadorpos.ServiceReference1.pruebaJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pruebaJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productos;
        
        public pruebaJSONRequestBody() {
        }
        
        public pruebaJSONRequestBody(string productos) {
            this.productos = productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pruebaJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pruebaJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.pruebaJSONResponseBody Body;
        
        public pruebaJSONResponse() {
        }
        
        public pruebaJSONResponse(salvadorpos.ServiceReference1.pruebaJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pruebaJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pruebaJSONResult;
        
        public pruebaJSONResponseBody() {
        }
        
        public pruebaJSONResponseBody(string pruebaJSONResult) {
            this.pruebaJSONResult = pruebaJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaTerminosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaTerminos", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaTerminosRequestBody Body;
        
        public ListaTerminosRequest() {
        }
        
        public ListaTerminosRequest(salvadorpos.ServiceReference1.ListaTerminosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaTerminosRequestBody {
        
        public ListaTerminosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaTerminosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaTerminosResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaTerminosResponseBody Body;
        
        public ListaTerminosResponse() {
        }
        
        public ListaTerminosResponse(salvadorpos.ServiceReference1.ListaTerminosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaTerminosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public salvadorpos.ServiceReference1.ArrayOfString ListaTerminosResult;
        
        public ListaTerminosResponseBody() {
        }
        
        public ListaTerminosResponseBody(salvadorpos.ServiceReference1.ArrayOfString ListaTerminosResult) {
            this.ListaTerminosResult = ListaTerminosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaMensajesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaMensajes", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaMensajesRequestBody Body;
        
        public ListaMensajesRequest() {
        }
        
        public ListaMensajesRequest(salvadorpos.ServiceReference1.ListaMensajesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaMensajesRequestBody {
        
        public ListaMensajesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaMensajesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaMensajesResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaMensajesResponseBody Body;
        
        public ListaMensajesResponse() {
        }
        
        public ListaMensajesResponse(salvadorpos.ServiceReference1.ListaMensajesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaMensajesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public salvadorpos.ServiceReference1.ArrayOfString ListaMensajesResult;
        
        public ListaMensajesResponseBody() {
        }
        
        public ListaMensajesResponseBody(salvadorpos.ServiceReference1.ArrayOfString ListaMensajesResult) {
            this.ListaMensajesResult = ListaMensajesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerAddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerAdd", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.CustomerAddRequestBody Body;
        
        public CustomerAddRequest() {
        }
        
        public CustomerAddRequest(salvadorpos.ServiceReference1.CustomerAddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerAddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Phone;
        
        public CustomerAddRequestBody() {
        }
        
        public CustomerAddRequestBody(string ListID, string FullName, string Email, string Phone) {
            this.ListID = ListID;
            this.FullName = FullName;
            this.Email = Email;
            this.Phone = Phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerAddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerAddResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.CustomerAddResponseBody Body;
        
        public CustomerAddResponse() {
        }
        
        public CustomerAddResponse(salvadorpos.ServiceReference1.CustomerAddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerAddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerAddResult;
        
        public CustomerAddResponseBody() {
        }
        
        public CustomerAddResponseBody(string CustomerAddResult) {
            this.CustomerAddResult = CustomerAddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomFieldAddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomFieldAdd", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.CustomFieldAddRequestBody Body;
        
        public CustomFieldAddRequest() {
        }
        
        public CustomFieldAddRequest(salvadorpos.ServiceReference1.CustomFieldAddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomFieldAddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string namefield;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string valuefield;
        
        public CustomFieldAddRequestBody() {
        }
        
        public CustomFieldAddRequestBody(string customerID, string namefield, string valuefield) {
            this.customerID = customerID;
            this.namefield = namefield;
            this.valuefield = valuefield;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomFieldAddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomFieldAddResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.CustomFieldAddResponseBody Body;
        
        public CustomFieldAddResponse() {
        }
        
        public CustomFieldAddResponse(salvadorpos.ServiceReference1.CustomFieldAddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomFieldAddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomFieldAddResult;
        
        public CustomFieldAddResponseBody() {
        }
        
        public CustomFieldAddResponseBody(string CustomFieldAddResult) {
            this.CustomFieldAddResult = CustomFieldAddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaImpuestosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaImpuestos", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaImpuestosRequestBody Body;
        
        public ListaImpuestosRequest() {
        }
        
        public ListaImpuestosRequest(salvadorpos.ServiceReference1.ListaImpuestosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaImpuestosRequestBody {
        
        public ListaImpuestosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaImpuestosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaImpuestosResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaImpuestosResponseBody Body;
        
        public ListaImpuestosResponse() {
        }
        
        public ListaImpuestosResponse(salvadorpos.ServiceReference1.ListaImpuestosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaImpuestosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public salvadorpos.ServiceReference1.ArrayOfString ListaImpuestosResult;
        
        public ListaImpuestosResponseBody() {
        }
        
        public ListaImpuestosResponseBody(salvadorpos.ServiceReference1.ArrayOfString ListaImpuestosResult) {
            this.ListaImpuestosResult = ListaImpuestosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaBodegasItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaBodegasItem", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaBodegasItemRequestBody Body;
        
        public ListaBodegasItemRequest() {
        }
        
        public ListaBodegasItemRequest(salvadorpos.ServiceReference1.ListaBodegasItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaBodegasItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idcliente;
        
        public ListaBodegasItemRequestBody() {
        }
        
        public ListaBodegasItemRequestBody(string idcliente) {
            this.idcliente = idcliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaBodegasItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaBodegasItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaBodegasItemResponseBody Body;
        
        public ListaBodegasItemResponse() {
        }
        
        public ListaBodegasItemResponse(salvadorpos.ServiceReference1.ListaBodegasItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaBodegasItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaBodegasItemResult;
        
        public ListaBodegasItemResponseBody() {
        }
        
        public ListaBodegasItemResponseBody(salvadorpos.ServiceReference1.ArrayOfString[] ListaBodegasItemResult) {
            this.ListaBodegasItemResult = ListaBodegasItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaArticulosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaArticulos", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaArticulosRequestBody Body;
        
        public ListaArticulosRequest() {
        }
        
        public ListaArticulosRequest(salvadorpos.ServiceReference1.ListaArticulosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaArticulosRequestBody {
        
        public ListaArticulosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaArticulosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaArticulosResponse", Namespace="http://tempuri.org/", Order=0)]
        public salvadorpos.ServiceReference1.ListaArticulosResponseBody Body;
        
        public ListaArticulosResponse() {
        }
        
        public ListaArticulosResponse(salvadorpos.ServiceReference1.ListaArticulosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaArticulosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaArticulosResult;
        
        public ListaArticulosResponseBody() {
        }
        
        public ListaArticulosResponseBody(salvadorpos.ServiceReference1.ArrayOfString[] ListaArticulosResult) {
            this.ListaArticulosResult = ListaArticulosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuickBooksWebRestSoapChannel : salvadorpos.ServiceReference1.QuickBooksWebRestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuickBooksWebRestSoapClient : System.ServiceModel.ClientBase<salvadorpos.ServiceReference1.QuickBooksWebRestSoap>, salvadorpos.ServiceReference1.QuickBooksWebRestSoap {
        
        public QuickBooksWebRestSoapClient() {
        }
        
        public QuickBooksWebRestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuickBooksWebRestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuickBooksWebRestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuickBooksWebRestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.ListaClientesResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaClientes(salvadorpos.ServiceReference1.ListaClientesRequest request) {
            return base.Channel.ListaClientes(request);
        }
        
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaClientes() {
            salvadorpos.ServiceReference1.ListaClientesRequest inValue = new salvadorpos.ServiceReference1.ListaClientesRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaClientesRequestBody();
            salvadorpos.ServiceReference1.ListaClientesResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaClientes(inValue);
            return retVal.Body.ListaClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaClientesResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaClientesAsync(salvadorpos.ServiceReference1.ListaClientesRequest request) {
            return base.Channel.ListaClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaClientesResponse> ListaClientesAsync() {
            salvadorpos.ServiceReference1.ListaClientesRequest inValue = new salvadorpos.ServiceReference1.ListaClientesRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaClientesRequestBody();
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.ListaDataExtCustomerResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaDataExtCustomer(salvadorpos.ServiceReference1.ListaDataExtCustomerRequest request) {
            return base.Channel.ListaDataExtCustomer(request);
        }
        
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaDataExtCustomer(string idcliente) {
            salvadorpos.ServiceReference1.ListaDataExtCustomerRequest inValue = new salvadorpos.ServiceReference1.ListaDataExtCustomerRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaDataExtCustomerRequestBody();
            inValue.Body.idcliente = idcliente;
            salvadorpos.ServiceReference1.ListaDataExtCustomerResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaDataExtCustomer(inValue);
            return retVal.Body.ListaDataExtCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaDataExtCustomerResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaDataExtCustomerAsync(salvadorpos.ServiceReference1.ListaDataExtCustomerRequest request) {
            return base.Channel.ListaDataExtCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaDataExtCustomerResponse> ListaDataExtCustomerAsync(string idcliente) {
            salvadorpos.ServiceReference1.ListaDataExtCustomerRequest inValue = new salvadorpos.ServiceReference1.ListaDataExtCustomerRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaDataExtCustomerRequestBody();
            inValue.Body.idcliente = idcliente;
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaDataExtCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.ListaPriceLevelsResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaPriceLevels(salvadorpos.ServiceReference1.ListaPriceLevelsRequest request) {
            return base.Channel.ListaPriceLevels(request);
        }
        
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaPriceLevels() {
            salvadorpos.ServiceReference1.ListaPriceLevelsRequest inValue = new salvadorpos.ServiceReference1.ListaPriceLevelsRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaPriceLevelsRequestBody();
            salvadorpos.ServiceReference1.ListaPriceLevelsResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaPriceLevels(inValue);
            return retVal.Body.ListaPriceLevelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaPriceLevelsResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaPriceLevelsAsync(salvadorpos.ServiceReference1.ListaPriceLevelsRequest request) {
            return base.Channel.ListaPriceLevelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaPriceLevelsResponse> ListaPriceLevelsAsync() {
            salvadorpos.ServiceReference1.ListaPriceLevelsRequest inValue = new salvadorpos.ServiceReference1.ListaPriceLevelsRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaPriceLevelsRequestBody();
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaPriceLevelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.InsertaFacturaResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.InsertaFactura(salvadorpos.ServiceReference1.InsertaFacturaRequest request) {
            return base.Channel.InsertaFactura(request);
        }
        
        public string InsertaFactura(string cliente, string template, string TxnDate, string DueDate, string ShipDate, string termino, string memo, string ItemSalesTax, string CustomerMsg, string productos) {
            salvadorpos.ServiceReference1.InsertaFacturaRequest inValue = new salvadorpos.ServiceReference1.InsertaFacturaRequest();
            inValue.Body = new salvadorpos.ServiceReference1.InsertaFacturaRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.template = template;
            inValue.Body.TxnDate = TxnDate;
            inValue.Body.DueDate = DueDate;
            inValue.Body.ShipDate = ShipDate;
            inValue.Body.termino = termino;
            inValue.Body.memo = memo;
            inValue.Body.ItemSalesTax = ItemSalesTax;
            inValue.Body.CustomerMsg = CustomerMsg;
            inValue.Body.productos = productos;
            salvadorpos.ServiceReference1.InsertaFacturaResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).InsertaFactura(inValue);
            return retVal.Body.InsertaFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.InsertaFacturaResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.InsertaFacturaAsync(salvadorpos.ServiceReference1.InsertaFacturaRequest request) {
            return base.Channel.InsertaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.InsertaFacturaResponse> InsertaFacturaAsync(string cliente, string template, string TxnDate, string DueDate, string ShipDate, string termino, string memo, string ItemSalesTax, string CustomerMsg, string productos) {
            salvadorpos.ServiceReference1.InsertaFacturaRequest inValue = new salvadorpos.ServiceReference1.InsertaFacturaRequest();
            inValue.Body = new salvadorpos.ServiceReference1.InsertaFacturaRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.template = template;
            inValue.Body.TxnDate = TxnDate;
            inValue.Body.DueDate = DueDate;
            inValue.Body.ShipDate = ShipDate;
            inValue.Body.termino = termino;
            inValue.Body.memo = memo;
            inValue.Body.ItemSalesTax = ItemSalesTax;
            inValue.Body.CustomerMsg = CustomerMsg;
            inValue.Body.productos = productos;
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).InsertaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.pruebaJSONResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.pruebaJSON(salvadorpos.ServiceReference1.pruebaJSONRequest request) {
            return base.Channel.pruebaJSON(request);
        }
        
        public string pruebaJSON(string productos) {
            salvadorpos.ServiceReference1.pruebaJSONRequest inValue = new salvadorpos.ServiceReference1.pruebaJSONRequest();
            inValue.Body = new salvadorpos.ServiceReference1.pruebaJSONRequestBody();
            inValue.Body.productos = productos;
            salvadorpos.ServiceReference1.pruebaJSONResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).pruebaJSON(inValue);
            return retVal.Body.pruebaJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.pruebaJSONResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.pruebaJSONAsync(salvadorpos.ServiceReference1.pruebaJSONRequest request) {
            return base.Channel.pruebaJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.pruebaJSONResponse> pruebaJSONAsync(string productos) {
            salvadorpos.ServiceReference1.pruebaJSONRequest inValue = new salvadorpos.ServiceReference1.pruebaJSONRequest();
            inValue.Body = new salvadorpos.ServiceReference1.pruebaJSONRequestBody();
            inValue.Body.productos = productos;
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).pruebaJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.ListaTerminosResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaTerminos(salvadorpos.ServiceReference1.ListaTerminosRequest request) {
            return base.Channel.ListaTerminos(request);
        }
        
        public salvadorpos.ServiceReference1.ArrayOfString ListaTerminos() {
            salvadorpos.ServiceReference1.ListaTerminosRequest inValue = new salvadorpos.ServiceReference1.ListaTerminosRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaTerminosRequestBody();
            salvadorpos.ServiceReference1.ListaTerminosResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaTerminos(inValue);
            return retVal.Body.ListaTerminosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaTerminosResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaTerminosAsync(salvadorpos.ServiceReference1.ListaTerminosRequest request) {
            return base.Channel.ListaTerminosAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaTerminosResponse> ListaTerminosAsync() {
            salvadorpos.ServiceReference1.ListaTerminosRequest inValue = new salvadorpos.ServiceReference1.ListaTerminosRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaTerminosRequestBody();
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaTerminosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.ListaMensajesResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaMensajes(salvadorpos.ServiceReference1.ListaMensajesRequest request) {
            return base.Channel.ListaMensajes(request);
        }
        
        public salvadorpos.ServiceReference1.ArrayOfString ListaMensajes() {
            salvadorpos.ServiceReference1.ListaMensajesRequest inValue = new salvadorpos.ServiceReference1.ListaMensajesRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaMensajesRequestBody();
            salvadorpos.ServiceReference1.ListaMensajesResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaMensajes(inValue);
            return retVal.Body.ListaMensajesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaMensajesResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaMensajesAsync(salvadorpos.ServiceReference1.ListaMensajesRequest request) {
            return base.Channel.ListaMensajesAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaMensajesResponse> ListaMensajesAsync() {
            salvadorpos.ServiceReference1.ListaMensajesRequest inValue = new salvadorpos.ServiceReference1.ListaMensajesRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaMensajesRequestBody();
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaMensajesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.CustomerAddResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.CustomerAdd(salvadorpos.ServiceReference1.CustomerAddRequest request) {
            return base.Channel.CustomerAdd(request);
        }
        
        public string CustomerAdd(string ListID, string FullName, string Email, string Phone) {
            salvadorpos.ServiceReference1.CustomerAddRequest inValue = new salvadorpos.ServiceReference1.CustomerAddRequest();
            inValue.Body = new salvadorpos.ServiceReference1.CustomerAddRequestBody();
            inValue.Body.ListID = ListID;
            inValue.Body.FullName = FullName;
            inValue.Body.Email = Email;
            inValue.Body.Phone = Phone;
            salvadorpos.ServiceReference1.CustomerAddResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).CustomerAdd(inValue);
            return retVal.Body.CustomerAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.CustomerAddResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.CustomerAddAsync(salvadorpos.ServiceReference1.CustomerAddRequest request) {
            return base.Channel.CustomerAddAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.CustomerAddResponse> CustomerAddAsync(string ListID, string FullName, string Email, string Phone) {
            salvadorpos.ServiceReference1.CustomerAddRequest inValue = new salvadorpos.ServiceReference1.CustomerAddRequest();
            inValue.Body = new salvadorpos.ServiceReference1.CustomerAddRequestBody();
            inValue.Body.ListID = ListID;
            inValue.Body.FullName = FullName;
            inValue.Body.Email = Email;
            inValue.Body.Phone = Phone;
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).CustomerAddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.CustomFieldAddResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.CustomFieldAdd(salvadorpos.ServiceReference1.CustomFieldAddRequest request) {
            return base.Channel.CustomFieldAdd(request);
        }
        
        public string CustomFieldAdd(string customerID, string namefield, string valuefield) {
            salvadorpos.ServiceReference1.CustomFieldAddRequest inValue = new salvadorpos.ServiceReference1.CustomFieldAddRequest();
            inValue.Body = new salvadorpos.ServiceReference1.CustomFieldAddRequestBody();
            inValue.Body.customerID = customerID;
            inValue.Body.namefield = namefield;
            inValue.Body.valuefield = valuefield;
            salvadorpos.ServiceReference1.CustomFieldAddResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).CustomFieldAdd(inValue);
            return retVal.Body.CustomFieldAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.CustomFieldAddResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.CustomFieldAddAsync(salvadorpos.ServiceReference1.CustomFieldAddRequest request) {
            return base.Channel.CustomFieldAddAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.CustomFieldAddResponse> CustomFieldAddAsync(string customerID, string namefield, string valuefield) {
            salvadorpos.ServiceReference1.CustomFieldAddRequest inValue = new salvadorpos.ServiceReference1.CustomFieldAddRequest();
            inValue.Body = new salvadorpos.ServiceReference1.CustomFieldAddRequestBody();
            inValue.Body.customerID = customerID;
            inValue.Body.namefield = namefield;
            inValue.Body.valuefield = valuefield;
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).CustomFieldAddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.ListaImpuestosResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaImpuestos(salvadorpos.ServiceReference1.ListaImpuestosRequest request) {
            return base.Channel.ListaImpuestos(request);
        }
        
        public salvadorpos.ServiceReference1.ArrayOfString ListaImpuestos() {
            salvadorpos.ServiceReference1.ListaImpuestosRequest inValue = new salvadorpos.ServiceReference1.ListaImpuestosRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaImpuestosRequestBody();
            salvadorpos.ServiceReference1.ListaImpuestosResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaImpuestos(inValue);
            return retVal.Body.ListaImpuestosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaImpuestosResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaImpuestosAsync(salvadorpos.ServiceReference1.ListaImpuestosRequest request) {
            return base.Channel.ListaImpuestosAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaImpuestosResponse> ListaImpuestosAsync() {
            salvadorpos.ServiceReference1.ListaImpuestosRequest inValue = new salvadorpos.ServiceReference1.ListaImpuestosRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaImpuestosRequestBody();
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaImpuestosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.ListaBodegasItemResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaBodegasItem(salvadorpos.ServiceReference1.ListaBodegasItemRequest request) {
            return base.Channel.ListaBodegasItem(request);
        }
        
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaBodegasItem(string idcliente) {
            salvadorpos.ServiceReference1.ListaBodegasItemRequest inValue = new salvadorpos.ServiceReference1.ListaBodegasItemRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaBodegasItemRequestBody();
            inValue.Body.idcliente = idcliente;
            salvadorpos.ServiceReference1.ListaBodegasItemResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaBodegasItem(inValue);
            return retVal.Body.ListaBodegasItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaBodegasItemResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaBodegasItemAsync(salvadorpos.ServiceReference1.ListaBodegasItemRequest request) {
            return base.Channel.ListaBodegasItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaBodegasItemResponse> ListaBodegasItemAsync(string idcliente) {
            salvadorpos.ServiceReference1.ListaBodegasItemRequest inValue = new salvadorpos.ServiceReference1.ListaBodegasItemRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaBodegasItemRequestBody();
            inValue.Body.idcliente = idcliente;
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaBodegasItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        salvadorpos.ServiceReference1.ListaArticulosResponse salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaArticulos(salvadorpos.ServiceReference1.ListaArticulosRequest request) {
            return base.Channel.ListaArticulos(request);
        }
        
        public salvadorpos.ServiceReference1.ArrayOfString[] ListaArticulos() {
            salvadorpos.ServiceReference1.ListaArticulosRequest inValue = new salvadorpos.ServiceReference1.ListaArticulosRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaArticulosRequestBody();
            salvadorpos.ServiceReference1.ListaArticulosResponse retVal = ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaArticulos(inValue);
            return retVal.Body.ListaArticulosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaArticulosResponse> salvadorpos.ServiceReference1.QuickBooksWebRestSoap.ListaArticulosAsync(salvadorpos.ServiceReference1.ListaArticulosRequest request) {
            return base.Channel.ListaArticulosAsync(request);
        }
        
        public System.Threading.Tasks.Task<salvadorpos.ServiceReference1.ListaArticulosResponse> ListaArticulosAsync() {
            salvadorpos.ServiceReference1.ListaArticulosRequest inValue = new salvadorpos.ServiceReference1.ListaArticulosRequest();
            inValue.Body = new salvadorpos.ServiceReference1.ListaArticulosRequestBody();
            return ((salvadorpos.ServiceReference1.QuickBooksWebRestSoap)(this)).ListaArticulosAsync(inValue);
        }
    }
}
