//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handler.QuickService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuickService.QuickBooksWebRestSoap")]
    public interface QuickBooksWebRestSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ParametrodeBusqueda del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaClientes", ReplyAction="*")]
        Handler.QuickService.ListaClientesResponse ListaClientes(Handler.QuickService.ListaClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.ListaClientesResponse> ListaClientesAsync(Handler.QuickService.ListaClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaFactura", ReplyAction="*")]
        Handler.QuickService.InsertaFacturaResponse InsertaFactura(Handler.QuickService.InsertaFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.InsertaFacturaResponse> InsertaFacturaAsync(Handler.QuickService.InsertaFacturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaDetaFactura", ReplyAction="*")]
        Handler.QuickService.InsertaDetaFacturaResponse InsertaDetaFactura(Handler.QuickService.InsertaDetaFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaDetaFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.InsertaDetaFacturaResponse> InsertaDetaFacturaAsync(Handler.QuickService.InsertaDetaFacturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaTerminosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaTerminos", ReplyAction="*")]
        Handler.QuickService.ListaTerminosResponse ListaTerminos(Handler.QuickService.ListaTerminosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaTerminos", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.ListaTerminosResponse> ListaTerminosAsync(Handler.QuickService.ListaTerminosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaMensajesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaMensajes", ReplyAction="*")]
        Handler.QuickService.ListaMensajesResponse ListaMensajes(Handler.QuickService.ListaMensajesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaMensajes", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.ListaMensajesResponse> ListaMensajesAsync(Handler.QuickService.ListaMensajesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaImpuestosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaImpuestos", ReplyAction="*")]
        Handler.QuickService.ListaImpuestosResponse ListaImpuestos(Handler.QuickService.ListaImpuestosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaImpuestos", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.ListaImpuestosResponse> ListaImpuestosAsync(Handler.QuickService.ListaImpuestosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idcliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaBodegasItem", ReplyAction="*")]
        Handler.QuickService.ListaBodegasItemResponse ListaBodegasItem(Handler.QuickService.ListaBodegasItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaBodegasItem", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.ListaBodegasItemResponse> ListaBodegasItemAsync(Handler.QuickService.ListaBodegasItemRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaArticulosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaArticulos", ReplyAction="*")]
        Handler.QuickService.ListaArticulosResponse ListaArticulos(Handler.QuickService.ListaArticulosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaArticulos", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.ListaArticulosResponse> ListaArticulosAsync(Handler.QuickService.ListaArticulosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento JsonString del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarFactura", ReplyAction="*")]
        Handler.QuickService.IngresarFacturaResponse IngresarFactura(Handler.QuickService.IngresarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<Handler.QuickService.IngresarFacturaResponse> IngresarFacturaAsync(Handler.QuickService.IngresarFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaClientes", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaClientesRequestBody Body;
        
        public ListaClientesRequest() {
        }
        
        public ListaClientesRequest(Handler.QuickService.ListaClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaClientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ParametrodeBusqueda;
        
        public ListaClientesRequestBody() {
        }
        
        public ListaClientesRequestBody(string ParametrodeBusqueda) {
            this.ParametrodeBusqueda = ParametrodeBusqueda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaClientesResponseBody Body;
        
        public ListaClientesResponse() {
        }
        
        public ListaClientesResponse(Handler.QuickService.ListaClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Handler.QuickService.ArrayOfString ListaClientesResult;
        
        public ListaClientesResponseBody() {
        }
        
        public ListaClientesResponseBody(Handler.QuickService.ArrayOfString ListaClientesResult) {
            this.ListaClientesResult = ListaClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaFactura", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.InsertaFacturaRequestBody Body;
        
        public InsertaFacturaRequest() {
        }
        
        public InsertaFacturaRequest(Handler.QuickService.InsertaFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertaFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoFacturaApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string termino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subtotal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string impuesto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string enviadoQB;
        
        public InsertaFacturaRequestBody() {
        }
        
        public InsertaFacturaRequestBody(int codigoFacturaApp, string cliente, string fecha, string termino, string mensaje, string subtotal, string impuesto, string total, string enviadoQB) {
            this.codigoFacturaApp = codigoFacturaApp;
            this.cliente = cliente;
            this.fecha = fecha;
            this.termino = termino;
            this.mensaje = mensaje;
            this.subtotal = subtotal;
            this.impuesto = impuesto;
            this.total = total;
            this.enviadoQB = enviadoQB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.InsertaFacturaResponseBody Body;
        
        public InsertaFacturaResponse() {
        }
        
        public InsertaFacturaResponse(Handler.QuickService.InsertaFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertaFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Handler.QuickService.ArrayOfString InsertaFacturaResult;
        
        public InsertaFacturaResponseBody() {
        }
        
        public InsertaFacturaResponseBody(Handler.QuickService.ArrayOfString InsertaFacturaResult) {
            this.InsertaFacturaResult = InsertaFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaDetaFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaDetaFactura", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.InsertaDetaFacturaRequestBody Body;
        
        public InsertaDetaFacturaRequest() {
        }
        
        public InsertaDetaFacturaRequest(Handler.QuickService.InsertaDetaFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertaDetaFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoFactura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int SQLID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string precioUnitario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string impuesto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string tipoImpuesto;
        
        public InsertaDetaFacturaRequestBody() {
        }
        
        public InsertaDetaFacturaRequestBody(int codigoFactura, int SQLID, string codigo, string descripcion, int cantidad, string precioUnitario, string total, string impuesto, string tipoImpuesto) {
            this.codigoFactura = codigoFactura;
            this.SQLID = SQLID;
            this.codigo = codigo;
            this.descripcion = descripcion;
            this.cantidad = cantidad;
            this.precioUnitario = precioUnitario;
            this.total = total;
            this.impuesto = impuesto;
            this.tipoImpuesto = tipoImpuesto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaDetaFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaDetaFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.InsertaDetaFacturaResponseBody Body;
        
        public InsertaDetaFacturaResponse() {
        }
        
        public InsertaDetaFacturaResponse(Handler.QuickService.InsertaDetaFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertaDetaFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Handler.QuickService.ArrayOfString InsertaDetaFacturaResult;
        
        public InsertaDetaFacturaResponseBody() {
        }
        
        public InsertaDetaFacturaResponseBody(Handler.QuickService.ArrayOfString InsertaDetaFacturaResult) {
            this.InsertaDetaFacturaResult = InsertaDetaFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaTerminosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaTerminos", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaTerminosRequestBody Body;
        
        public ListaTerminosRequest() {
        }
        
        public ListaTerminosRequest(Handler.QuickService.ListaTerminosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaTerminosRequestBody {
        
        public ListaTerminosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaTerminosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaTerminosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaTerminosResponseBody Body;
        
        public ListaTerminosResponse() {
        }
        
        public ListaTerminosResponse(Handler.QuickService.ListaTerminosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaTerminosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Handler.QuickService.ArrayOfString ListaTerminosResult;
        
        public ListaTerminosResponseBody() {
        }
        
        public ListaTerminosResponseBody(Handler.QuickService.ArrayOfString ListaTerminosResult) {
            this.ListaTerminosResult = ListaTerminosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaMensajesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaMensajes", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaMensajesRequestBody Body;
        
        public ListaMensajesRequest() {
        }
        
        public ListaMensajesRequest(Handler.QuickService.ListaMensajesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaMensajesRequestBody {
        
        public ListaMensajesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaMensajesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaMensajesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaMensajesResponseBody Body;
        
        public ListaMensajesResponse() {
        }
        
        public ListaMensajesResponse(Handler.QuickService.ListaMensajesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaMensajesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Handler.QuickService.ArrayOfString ListaMensajesResult;
        
        public ListaMensajesResponseBody() {
        }
        
        public ListaMensajesResponseBody(Handler.QuickService.ArrayOfString ListaMensajesResult) {
            this.ListaMensajesResult = ListaMensajesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaImpuestosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaImpuestos", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaImpuestosRequestBody Body;
        
        public ListaImpuestosRequest() {
        }
        
        public ListaImpuestosRequest(Handler.QuickService.ListaImpuestosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaImpuestosRequestBody {
        
        public ListaImpuestosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaImpuestosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaImpuestosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaImpuestosResponseBody Body;
        
        public ListaImpuestosResponse() {
        }
        
        public ListaImpuestosResponse(Handler.QuickService.ListaImpuestosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaImpuestosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Handler.QuickService.ArrayOfString ListaImpuestosResult;
        
        public ListaImpuestosResponseBody() {
        }
        
        public ListaImpuestosResponseBody(Handler.QuickService.ArrayOfString ListaImpuestosResult) {
            this.ListaImpuestosResult = ListaImpuestosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaBodegasItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaBodegasItem", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaBodegasItemRequestBody Body;
        
        public ListaBodegasItemRequest() {
        }
        
        public ListaBodegasItemRequest(Handler.QuickService.ListaBodegasItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaBodegasItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idcliente;
        
        public ListaBodegasItemRequestBody() {
        }
        
        public ListaBodegasItemRequestBody(string idcliente) {
            this.idcliente = idcliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaBodegasItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaBodegasItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaBodegasItemResponseBody Body;
        
        public ListaBodegasItemResponse() {
        }
        
        public ListaBodegasItemResponse(Handler.QuickService.ListaBodegasItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaBodegasItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Handler.QuickService.ArrayOfString[] ListaBodegasItemResult;
        
        public ListaBodegasItemResponseBody() {
        }
        
        public ListaBodegasItemResponseBody(Handler.QuickService.ArrayOfString[] ListaBodegasItemResult) {
            this.ListaBodegasItemResult = ListaBodegasItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaArticulosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaArticulos", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaArticulosRequestBody Body;
        
        public ListaArticulosRequest() {
        }
        
        public ListaArticulosRequest(Handler.QuickService.ListaArticulosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaArticulosRequestBody {
        
        public ListaArticulosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaArticulosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaArticulosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.ListaArticulosResponseBody Body;
        
        public ListaArticulosResponse() {
        }
        
        public ListaArticulosResponse(Handler.QuickService.ListaArticulosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaArticulosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Handler.QuickService.ArrayOfString[] ListaArticulosResult;
        
        public ListaArticulosResponseBody() {
        }
        
        public ListaArticulosResponseBody(Handler.QuickService.ArrayOfString[] ListaArticulosResult) {
            this.ListaArticulosResult = ListaArticulosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarFactura", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.IngresarFacturaRequestBody Body;
        
        public IngresarFacturaRequest() {
        }
        
        public IngresarFacturaRequest(Handler.QuickService.IngresarFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresarFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JsonString;
        
        public IngresarFacturaRequestBody() {
        }
        
        public IngresarFacturaRequestBody(string JsonString) {
            this.JsonString = JsonString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Handler.QuickService.IngresarFacturaResponseBody Body;
        
        public IngresarFacturaResponse() {
        }
        
        public IngresarFacturaResponse(Handler.QuickService.IngresarFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresarFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IngresarFacturaResult;
        
        public IngresarFacturaResponseBody() {
        }
        
        public IngresarFacturaResponseBody(string IngresarFacturaResult) {
            this.IngresarFacturaResult = IngresarFacturaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuickBooksWebRestSoapChannel : Handler.QuickService.QuickBooksWebRestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuickBooksWebRestSoapClient : System.ServiceModel.ClientBase<Handler.QuickService.QuickBooksWebRestSoap>, Handler.QuickService.QuickBooksWebRestSoap {
        
        public QuickBooksWebRestSoapClient() {
        }
        
        public QuickBooksWebRestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuickBooksWebRestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuickBooksWebRestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuickBooksWebRestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.ListaClientesResponse Handler.QuickService.QuickBooksWebRestSoap.ListaClientes(Handler.QuickService.ListaClientesRequest request) {
            return base.Channel.ListaClientes(request);
        }
        
        public Handler.QuickService.ArrayOfString ListaClientes(string ParametrodeBusqueda) {
            Handler.QuickService.ListaClientesRequest inValue = new Handler.QuickService.ListaClientesRequest();
            inValue.Body = new Handler.QuickService.ListaClientesRequestBody();
            inValue.Body.ParametrodeBusqueda = ParametrodeBusqueda;
            Handler.QuickService.ListaClientesResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaClientes(inValue);
            return retVal.Body.ListaClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.ListaClientesResponse> Handler.QuickService.QuickBooksWebRestSoap.ListaClientesAsync(Handler.QuickService.ListaClientesRequest request) {
            return base.Channel.ListaClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.ListaClientesResponse> ListaClientesAsync(string ParametrodeBusqueda) {
            Handler.QuickService.ListaClientesRequest inValue = new Handler.QuickService.ListaClientesRequest();
            inValue.Body = new Handler.QuickService.ListaClientesRequestBody();
            inValue.Body.ParametrodeBusqueda = ParametrodeBusqueda;
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.InsertaFacturaResponse Handler.QuickService.QuickBooksWebRestSoap.InsertaFactura(Handler.QuickService.InsertaFacturaRequest request) {
            return base.Channel.InsertaFactura(request);
        }
        
        public Handler.QuickService.ArrayOfString InsertaFactura(int codigoFacturaApp, string cliente, string fecha, string termino, string mensaje, string subtotal, string impuesto, string total, string enviadoQB) {
            Handler.QuickService.InsertaFacturaRequest inValue = new Handler.QuickService.InsertaFacturaRequest();
            inValue.Body = new Handler.QuickService.InsertaFacturaRequestBody();
            inValue.Body.codigoFacturaApp = codigoFacturaApp;
            inValue.Body.cliente = cliente;
            inValue.Body.fecha = fecha;
            inValue.Body.termino = termino;
            inValue.Body.mensaje = mensaje;
            inValue.Body.subtotal = subtotal;
            inValue.Body.impuesto = impuesto;
            inValue.Body.total = total;
            inValue.Body.enviadoQB = enviadoQB;
            Handler.QuickService.InsertaFacturaResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).InsertaFactura(inValue);
            return retVal.Body.InsertaFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.InsertaFacturaResponse> Handler.QuickService.QuickBooksWebRestSoap.InsertaFacturaAsync(Handler.QuickService.InsertaFacturaRequest request) {
            return base.Channel.InsertaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.InsertaFacturaResponse> InsertaFacturaAsync(int codigoFacturaApp, string cliente, string fecha, string termino, string mensaje, string subtotal, string impuesto, string total, string enviadoQB) {
            Handler.QuickService.InsertaFacturaRequest inValue = new Handler.QuickService.InsertaFacturaRequest();
            inValue.Body = new Handler.QuickService.InsertaFacturaRequestBody();
            inValue.Body.codigoFacturaApp = codigoFacturaApp;
            inValue.Body.cliente = cliente;
            inValue.Body.fecha = fecha;
            inValue.Body.termino = termino;
            inValue.Body.mensaje = mensaje;
            inValue.Body.subtotal = subtotal;
            inValue.Body.impuesto = impuesto;
            inValue.Body.total = total;
            inValue.Body.enviadoQB = enviadoQB;
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).InsertaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.InsertaDetaFacturaResponse Handler.QuickService.QuickBooksWebRestSoap.InsertaDetaFactura(Handler.QuickService.InsertaDetaFacturaRequest request) {
            return base.Channel.InsertaDetaFactura(request);
        }
        
        public Handler.QuickService.ArrayOfString InsertaDetaFactura(int codigoFactura, int SQLID, string codigo, string descripcion, int cantidad, string precioUnitario, string total, string impuesto, string tipoImpuesto) {
            Handler.QuickService.InsertaDetaFacturaRequest inValue = new Handler.QuickService.InsertaDetaFacturaRequest();
            inValue.Body = new Handler.QuickService.InsertaDetaFacturaRequestBody();
            inValue.Body.codigoFactura = codigoFactura;
            inValue.Body.SQLID = SQLID;
            inValue.Body.codigo = codigo;
            inValue.Body.descripcion = descripcion;
            inValue.Body.cantidad = cantidad;
            inValue.Body.precioUnitario = precioUnitario;
            inValue.Body.total = total;
            inValue.Body.impuesto = impuesto;
            inValue.Body.tipoImpuesto = tipoImpuesto;
            Handler.QuickService.InsertaDetaFacturaResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).InsertaDetaFactura(inValue);
            return retVal.Body.InsertaDetaFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.InsertaDetaFacturaResponse> Handler.QuickService.QuickBooksWebRestSoap.InsertaDetaFacturaAsync(Handler.QuickService.InsertaDetaFacturaRequest request) {
            return base.Channel.InsertaDetaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.InsertaDetaFacturaResponse> InsertaDetaFacturaAsync(int codigoFactura, int SQLID, string codigo, string descripcion, int cantidad, string precioUnitario, string total, string impuesto, string tipoImpuesto) {
            Handler.QuickService.InsertaDetaFacturaRequest inValue = new Handler.QuickService.InsertaDetaFacturaRequest();
            inValue.Body = new Handler.QuickService.InsertaDetaFacturaRequestBody();
            inValue.Body.codigoFactura = codigoFactura;
            inValue.Body.SQLID = SQLID;
            inValue.Body.codigo = codigo;
            inValue.Body.descripcion = descripcion;
            inValue.Body.cantidad = cantidad;
            inValue.Body.precioUnitario = precioUnitario;
            inValue.Body.total = total;
            inValue.Body.impuesto = impuesto;
            inValue.Body.tipoImpuesto = tipoImpuesto;
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).InsertaDetaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.ListaTerminosResponse Handler.QuickService.QuickBooksWebRestSoap.ListaTerminos(Handler.QuickService.ListaTerminosRequest request) {
            return base.Channel.ListaTerminos(request);
        }
        
        public Handler.QuickService.ArrayOfString ListaTerminos() {
            Handler.QuickService.ListaTerminosRequest inValue = new Handler.QuickService.ListaTerminosRequest();
            inValue.Body = new Handler.QuickService.ListaTerminosRequestBody();
            Handler.QuickService.ListaTerminosResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaTerminos(inValue);
            return retVal.Body.ListaTerminosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.ListaTerminosResponse> Handler.QuickService.QuickBooksWebRestSoap.ListaTerminosAsync(Handler.QuickService.ListaTerminosRequest request) {
            return base.Channel.ListaTerminosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.ListaTerminosResponse> ListaTerminosAsync() {
            Handler.QuickService.ListaTerminosRequest inValue = new Handler.QuickService.ListaTerminosRequest();
            inValue.Body = new Handler.QuickService.ListaTerminosRequestBody();
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaTerminosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.ListaMensajesResponse Handler.QuickService.QuickBooksWebRestSoap.ListaMensajes(Handler.QuickService.ListaMensajesRequest request) {
            return base.Channel.ListaMensajes(request);
        }
        
        public Handler.QuickService.ArrayOfString ListaMensajes() {
            Handler.QuickService.ListaMensajesRequest inValue = new Handler.QuickService.ListaMensajesRequest();
            inValue.Body = new Handler.QuickService.ListaMensajesRequestBody();
            Handler.QuickService.ListaMensajesResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaMensajes(inValue);
            return retVal.Body.ListaMensajesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.ListaMensajesResponse> Handler.QuickService.QuickBooksWebRestSoap.ListaMensajesAsync(Handler.QuickService.ListaMensajesRequest request) {
            return base.Channel.ListaMensajesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.ListaMensajesResponse> ListaMensajesAsync() {
            Handler.QuickService.ListaMensajesRequest inValue = new Handler.QuickService.ListaMensajesRequest();
            inValue.Body = new Handler.QuickService.ListaMensajesRequestBody();
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaMensajesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.ListaImpuestosResponse Handler.QuickService.QuickBooksWebRestSoap.ListaImpuestos(Handler.QuickService.ListaImpuestosRequest request) {
            return base.Channel.ListaImpuestos(request);
        }
        
        public Handler.QuickService.ArrayOfString ListaImpuestos() {
            Handler.QuickService.ListaImpuestosRequest inValue = new Handler.QuickService.ListaImpuestosRequest();
            inValue.Body = new Handler.QuickService.ListaImpuestosRequestBody();
            Handler.QuickService.ListaImpuestosResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaImpuestos(inValue);
            return retVal.Body.ListaImpuestosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.ListaImpuestosResponse> Handler.QuickService.QuickBooksWebRestSoap.ListaImpuestosAsync(Handler.QuickService.ListaImpuestosRequest request) {
            return base.Channel.ListaImpuestosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.ListaImpuestosResponse> ListaImpuestosAsync() {
            Handler.QuickService.ListaImpuestosRequest inValue = new Handler.QuickService.ListaImpuestosRequest();
            inValue.Body = new Handler.QuickService.ListaImpuestosRequestBody();
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaImpuestosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.ListaBodegasItemResponse Handler.QuickService.QuickBooksWebRestSoap.ListaBodegasItem(Handler.QuickService.ListaBodegasItemRequest request) {
            return base.Channel.ListaBodegasItem(request);
        }
        
        public Handler.QuickService.ArrayOfString[] ListaBodegasItem(string idcliente) {
            Handler.QuickService.ListaBodegasItemRequest inValue = new Handler.QuickService.ListaBodegasItemRequest();
            inValue.Body = new Handler.QuickService.ListaBodegasItemRequestBody();
            inValue.Body.idcliente = idcliente;
            Handler.QuickService.ListaBodegasItemResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaBodegasItem(inValue);
            return retVal.Body.ListaBodegasItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.ListaBodegasItemResponse> Handler.QuickService.QuickBooksWebRestSoap.ListaBodegasItemAsync(Handler.QuickService.ListaBodegasItemRequest request) {
            return base.Channel.ListaBodegasItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.ListaBodegasItemResponse> ListaBodegasItemAsync(string idcliente) {
            Handler.QuickService.ListaBodegasItemRequest inValue = new Handler.QuickService.ListaBodegasItemRequest();
            inValue.Body = new Handler.QuickService.ListaBodegasItemRequestBody();
            inValue.Body.idcliente = idcliente;
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaBodegasItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.ListaArticulosResponse Handler.QuickService.QuickBooksWebRestSoap.ListaArticulos(Handler.QuickService.ListaArticulosRequest request) {
            return base.Channel.ListaArticulos(request);
        }
        
        public Handler.QuickService.ArrayOfString[] ListaArticulos() {
            Handler.QuickService.ListaArticulosRequest inValue = new Handler.QuickService.ListaArticulosRequest();
            inValue.Body = new Handler.QuickService.ListaArticulosRequestBody();
            Handler.QuickService.ListaArticulosResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaArticulos(inValue);
            return retVal.Body.ListaArticulosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.ListaArticulosResponse> Handler.QuickService.QuickBooksWebRestSoap.ListaArticulosAsync(Handler.QuickService.ListaArticulosRequest request) {
            return base.Channel.ListaArticulosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.ListaArticulosResponse> ListaArticulosAsync() {
            Handler.QuickService.ListaArticulosRequest inValue = new Handler.QuickService.ListaArticulosRequest();
            inValue.Body = new Handler.QuickService.ListaArticulosRequestBody();
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).ListaArticulosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Handler.QuickService.IngresarFacturaResponse Handler.QuickService.QuickBooksWebRestSoap.IngresarFactura(Handler.QuickService.IngresarFacturaRequest request) {
            return base.Channel.IngresarFactura(request);
        }
        
        public string IngresarFactura(string JsonString) {
            Handler.QuickService.IngresarFacturaRequest inValue = new Handler.QuickService.IngresarFacturaRequest();
            inValue.Body = new Handler.QuickService.IngresarFacturaRequestBody();
            inValue.Body.JsonString = JsonString;
            Handler.QuickService.IngresarFacturaResponse retVal = ((Handler.QuickService.QuickBooksWebRestSoap)(this)).IngresarFactura(inValue);
            return retVal.Body.IngresarFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Handler.QuickService.IngresarFacturaResponse> Handler.QuickService.QuickBooksWebRestSoap.IngresarFacturaAsync(Handler.QuickService.IngresarFacturaRequest request) {
            return base.Channel.IngresarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Handler.QuickService.IngresarFacturaResponse> IngresarFacturaAsync(string JsonString) {
            Handler.QuickService.IngresarFacturaRequest inValue = new Handler.QuickService.IngresarFacturaRequest();
            inValue.Body = new Handler.QuickService.IngresarFacturaRequestBody();
            inValue.Body.JsonString = JsonString;
            return ((Handler.QuickService.QuickBooksWebRestSoap)(this)).IngresarFacturaAsync(inValue);
        }
    }
}
